### ISSUE TITLE
Fixierung der Risk-Level Skala

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#15]
Siehe Issue 6: Vorschlag von Leo:

"bei unter 1 satt-grün, bei 2 grün, bei 3 grün-gelb, bei 4 gelb, bei 5-6 orange, bei 7-8 rot, bei 9-10 dunkelrot oder so, was halt gut aussieht"

Skala 1 -10:
1 ist nicht bedrohlich - 10 ist übel 
Bitte äußert eure Meinung dazu

**Comment by lengers** [comment]
Übernommen, es fand seit Eröffnung des Tickets keine Diskussion statt. Beantrage Schließung @JazminWhy
