### ISSUE TITLE
Farbschemata festlegen

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#16]
Wie belegen wir die 7 Standardfarben der Angular-Charts?

=> innerhalb der blauen Farbfamilie?? (dunkelblau ist schlecht, hellblau ist sicher)

=> mit Informationsgehalt? Ampelfarben enthalten? (rot ist schlecht, grün ist sicher)

**Comment by lengers** [comment]
@JazminWhy @mimattern @LarsThie @HendrikMdy 
Entscheidung innerhalb der nächsten 48 Stunden hier, ansonsten bleibt es beim Default
