### ISSUE TITLE
Dashboard: Neue Kacheln 

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#17]
=> Anzahl der Geräte

=> aus großer Kachel "Aktionen" Mehrere Kleine Kacheln machen

----> Verlinkung zu Devices-Seite
----> Export Scan

**Comment by lengers** [comment]
Wollen wir "Export Scan haben? @JazminWhy Ansonsten wäre das hier nämlich durch. 

Exportieren macht, da JSON, nicht wirklich viel Sinn. User, die damit was anfangen können, benutzen dafür die API...
