### ISSUE TITLE
[Bug] mdDialog not on top

### ISSUE THREAD

**Issue by mihoppe** [lengers/ganymed-fallstudie#31]
Wenn man sich Scan anschaut, ist das Fenster NICHT in der höchsten Ebene (Vordergrund), daher kann es passieren, dass der Name des Scans unter der Navigationsleiste verborgen wird.

![scans_nicht_im_vordergrund](https://user-images.githubusercontent.com/19573299/28118118-2f273ec4-6710-11e7-96fe-ad1204a908fd.JPG)

**Comment by lengers** [comment]
Fixed
