### ISSUE TITLE
design-dokument: frontend beschreiben

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#36]
Public => meint sichtbar für den Client

Aufteilung der Beschreibung wie die Komponenten im Projekt aufgeteilt sind (asset, somponents, services ..)
=> Aufgabe der Views beschreiben
=> passendes ALTES MOCKUP dazu
nach Input von Leo / Henny => Evolution zu aktuellem Setup aufzeigen
=> am Ende finalen Screenshot einfügen

> Ich mache eine Beispiel - Beschreibung
> danach gebe ich Bescheid  und ihr, Lars + Michael, teilt euch die Beschreibungen auf.

**Comment by mihoppe** [comment]
Aufgabe ist soweit fertig, habe sie alleine gemacht, daher sollte jemand mit Ahnung nochmals drüberschauen, ob die APIs richtig beschrieben sind und ob die beschriebenen Änderungen von Mockup zum finalen Screenshot stimmen. Habe an den entsprechenden Stellen je einen Kommentar ins Dokument eingefügt, sodass ihr die Themen schnell findet.
