### ISSUE TITLE
Umbenennung des einen Scans in #Mock in einen sinnvollen Namen 

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#37]

**Comment by lengers** [comment]
Das **ist** ein sinnvoller Name, nämlich die UUID des Scans. So verwalten wir die. Diese Namensgebung ist immer eindeutig und ist auch der Identifier in der DB. Für jeden Scan wird ein neues Dokument mit der UUID als Scan angelegt, dieser Scan ist nur, um zu zeigen, wie Scans aussehen.
