### ISSUE TITLE
Chart: Verwundbare Dienste - skaliert nicht

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#49]
Siehe Foto
![img-20170716-wa0028](https://user-images.githubusercontent.com/29035233/28250028-dd366ea6-6a60-11e7-81c4-14e1c7d9a95a.jpg)

**Comment by lengers** [comment]
Wenn mir jemand sagt, wie man ChartJS dahin kriegt, dynamisch mitzuwachsen, fixe ich das gerne

**Comment by JazminWhy** [comment]
Das könnte sich doch Michael oder Henny mal genauer anschauen :).

**Comment by JazminWhy** [comment]
Laut Leo liegt es am Regex =>

**Comment by JazminWhy** [comment]
https://stackoverflow.com/questions/28990708/chartjs-how-to-set-max-and-min-value-for-y-axis

**Comment by JazminWhy** [comment]
https://github.com/jtblin/angular-chart.js/issues/596

$scope.options = {
  scales: {
    yAxes: [
      {
        ticks: {beginAtZero:true,max:maxValue}
      }
    ]
  }
 }
