### ISSUE TITLE
Server - Uhrzeit

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#53]
Sollen/können wir die Uhrzeit anpassen?

Scan gestartet 20:12 

=> lt. Oberfläche 18:12
![image](https://user-images.githubusercontent.com/29035233/28250187-5ea3a236-6a63-11e7-8764-181e8b87b3c8.png)

**Comment by lengers** [comment]
Hinweis auf UTC eingefügt
