### ISSUE TITLE
Scan - Bug

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#54]
Nachdem man sich einen Scan aus der Liste genauer angesehen hat und den Dialog schließt, taucht die Liste nicht wieder auf

**Comment by lengers** [comment]
cannot reproduce

**Comment by JazminWhy** [comment]
In Google Chrome:

/api/scan/results/ee69a962-560b-454d-a9c2-cd5964bbfb25 
Failed to load resource: the server responded with a status of 502 ()

{"status":"error","data":"You are not authorized to access this endpoint"}

![image](https://user-images.githubusercontent.com/29035233/28250471-c8e1b9c0-6a69-11e7-812f-cfdd2b0648bd.png)

**Comment by lengers** [comment]
Liegt an dem dauernden Zurücksetzen des Containers. Not a real bug

**Comment by JazminWhy** [comment]
Okay

Am 16.07.2017 21:11 schrieb "lengers" <notifications@github.com>:

Liegt an dem dauernden Zurücksetzen des Containers. Not a real bug

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/lengers/ganymed-fallstudie/issues/54#issuecomment-315630310>,
or mute the thread
