### ISSUE TITLE
Mailbenachrichtigungen

### ISSUE THREAD

**Issue by JazminWhy** [lengers/ganymed-fallstudie#58]
Wenn man Benachrichtigungen bestätigt => sich ausloggt => nach dem wiedereinloggen => die benachrichtigungen sind nicht aktiviert.

Daran ändert auch der Speicher Button nichts.

**Comment by JazminWhy** [comment]
dasselbe Problem wenn man aktiviert und die Seite (zB auf Scans wechselt) und wieder zurück zu Accounts geht

**Comment by lengers** [comment]
Cannot reproduce

**Comment by JazminWhy** [comment]
passt
